<?php

namespace AppBundle\Repository;

/**
 * AbaccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbaccountRepository extends \Doctrine\ORM\EntityRepository
{
}
