<?php

namespace AppBundle\Repository;

/**
 * TransactiondetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactiondetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
