abaccount_index:
    path:     /
    defaults: { _controller: "AppBundle:ABAccount:index" }
    methods:  GET

abaccount_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:ABAccount:show" }
    methods:  GET

abaccount_new:
    path:     /new
    defaults: { _controller: "AppBundle:ABAccount:new" }
    methods:  [GET, POST]

abaccount_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:ABAccount:edit" }
    methods:  [GET, POST]

abaccount_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:ABAccount:delete" }
    methods:  DELETE
